version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_MEDODS
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: MEDODS
      POSTGRES_USER: senya
      POSTGRES_PASSWORD: 1q2w3e4r5t
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U senya -d postgres" ]
        interval: 5s
        retries: 5

  api:
    container_name: api_MEDODS
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      ADDRESS: ":8901"
      DATABASE_HOST: "db"
      DATABASE_PORT: "5432"
      DATABASE_USER: "senya"
      DATABASE_PASSWORD: "1q2w3e4r5t"
      DATABASE_NAME: "MEDODS"
      DATABASE_SSL_MODE: "disable"
      ACCESS_KEY: "f4pq3792h3dy4g82o63R84P265o3874wgfiy2p947gf7qo5hcnbvtbo8y2c9upnox3q9E3"
      REFRESH_KEY: "x53416ucertiyvuybiunb5yp6no78iu65cr34exqyto839p28u320kjfnubviry3294bdf"
      LIFETIME_ACCESS: "15m"
      LIFETIME_REFRESH: "24h"
    ports:
      - "8901:8901"